### PR TITLE
commonmark-v2

### PR DESCRIPTION
**Pull request by usernotnull**
- Bump min PHP to 7.4
- Bump League\CommonMark to ^2.0
- Fixed Tests

### CODE REVIEW

**Comment by simonvomeyser** [comment]
Hey, thanks for the PR :) 

can you please provide a description (maybe from the issue) and more importantly fix the tests for this PR? 

I will be able to look into this next monday I hope, if you added the things above.

This might require a new major version since it not only adds Support vor CommonMark 2.0 but seems breaks compatibility with the previous version

Again thanks for contributing 👍

**Comment by usernotnull** [comment]
I'm a hobbyist, never did tests before...
Time to get my feet wet :)

Btw I'll do a few more changes and also bumping min PHP to 7.4 since "Typed properties are only allowed since PHP 7.4".

Definitely needs a major version bump yes.

**Comment by simonvomeyser** [comment]
I've no idea what I'm doing here either ¯\_(ツ)_/¯ but the tests should be quite straightforward :) 

The suggested changes sound reasonable, could be ` "php": "^7.4 || ^8.0",` then like in the commonmark package 👍

**Comment by usernotnull** [comment]
Done... tests passing and description added.
Easier than I thought :)

**Comment by simonvomeyser** [comment]
Hey, cool, looked into it. To complete this, we would need to update the readme, could you do this as a last step? 

I will maybe then link the hash of the old readme so we can tell people how to install the 1.x version in one line, like "If you are using commonmark v.1.x click here.

Thanks for the contribution already, really appreciate your work :)

**Comment by usernotnull** [comment]
Sorry for the delay, was really busy...
Here you go, I updated the readme codeblocks.
You can update the readme according to your preference concerning this library's versioning.

**Comment by simonvomeyser** [comment]
Hey, no problem 'bout the busyness, I am quite in a stretch too atm, so this might take some time. But thanks a lot for all your effort already!

**Pull request merged**
